/* -*- Mode: Java; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* vim: set shiftwidth=2 tabstop=2 autoindent cindent expandtab: */

var OWNERS = {
  "AudioChannel": "Marco Chen",
  "Bluetooth": "Marco Chen",
  "Build Config": "Dylan Oliver",
  "DOM: Core & HTML": "Andrew Overholt",
  "DOM": "Andrew Overholt",
  "DOM: Contacts": "David Scravaglieri",
  "DOM: Device Interfaces": "Andrew Overholt",
  "Gaia": "Vivien Nicolas",
  "Gaia::Browser": "Gregor Wagner",
  "Gaia::Calendar": "Dylan Oliver",
  "Gaia::Camera": "David Flanagan",
  "Gaia::Clock": "Dylan Oliver",
  "Gaia::Contacts": "David Scravaglieri",
  "Gaia::Dialer": "David Scravaglieri",
  "Gaia::E-Mail": "Andrew Sutherland",
  "Gaia::Everything.me": "Gregor Wagner",
  "Gaia::First Time Experience": "Gregor Wagner",
  "Gaia::FMRadio": "Hema Koka",
  "Gaia::Gallery": "Hema Koka",
  "Gaia::Homescreen": "Gregor Wagner",
  "Gaia::Keyboard": "Tim Chien",
  "Gaia::Music": "Hema Koka",
  "Gaia::Search": "Gregor Wagner",
  "Gaia::Settings": "Tim Chien",
  "Gaia::SMS": "David Scravaglieri",
  "Gaia::System": "Tim Chien & Gregor Wagner",
  "Gaia::System::Browser Chrome": "Gregor Wagner",
  "Gaia::System::Lockscreen": "Tim Chien",
  "Gaia::System::Window Mgmt": "Tim Chien",
  "General Automation": "Jonathan Griffin",
  "Geolocation": "Doug Turner",
  "JavaScript Engine": "Naveed Ihsanullah",
  "Networking": "Jason Duell",
  "Panning and Zooming": "Milan Sreckovic",
  "Performance": "Mike Lee",
  "Runtime": "Fabrice Desré",
  "RIL": "Ken Chang",
  "Graphics": "Milan Sreckovic",
};
